spring:
  datasource:
    url: jdbc:mysql://localhost:3306/air_ticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ytq20010626
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true # 设置返回字段不为空，前端不报错
